name: lint-tests-and-coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-tests-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run tests
        run: npm test
