name: lint-tests-and-coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-tests-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Set NODE_PATH
        run: echo "NODE_PATH=src" >> $GITHUB_ENV
      - name: run tests
        run: npm test
